version: "3.8"
services:
  ncc-scoutsuite:
    image: ncc-scoutsuite:23-5-23
    env_file:
      - config/build.env
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VCS_REF=${VCS_REF}
        - VCS_URL=${VCS_URL}
        - VERSION=${VERSION}
        - BUILD_DATE=${BUILD_DATE}
        - VENDOR=${VENDOR}
        - NAME=${NAME}
        - IMAGE_NAME=${IMAGE_NAME}
        - DESCRIPTION=${DESCRIPTION}
